RunAll:
	make ./1Generator/makefile
	make ./2Codierung/makefile
	make ./3Fehlerteufel/makefile
	make ./4Decodierung/makefile

clearall:
	make ./1Generator/makefile clearall
	make ./2Codierung/makefile clearall
	make ./3Fehlerteufel/makefile clearall
	make ./4Decodierung/makefile clearall

deleteFiles:
	rm -f ./Dateien/*